### ISSUE TITLE
Why did you use the relationship belongsTo in the model emailconfirmation for userId

### ISSUE THREAD

**Issue by vega-7** [phalcon/vokuro#100]
Correct me if im wrong , maybe im not understanding correctly the use of relationship , but im 
wondering why in this scenario its not more appropiate the  --- hasOne --- relationship because you only need to registered and validated just one user, and this will appear only once in the table, right?

**Comment by sergeyklay** [comment]
What table/model doe you mean?

**Comment by vega-7** [comment]
Hi sergey  the table is email_confirmation / EmailConfirmations.php

**Comment by sergeyklay** [comment]
There is two use cases.

User can't change email

`hasOne` should be defined in the parent model (`Users`) and `belongsTo` should be defined in the child model `EmailConfirmations`. In this case a user has one email confirmation and that email confirmation belongs to one user.

User can change email:

`hasMany` should be defined in the parent model (`Users`) and `belongsTo` should be defined in the child model `EmailConfirmations`. In this case a user has many email confirmations and each email confirmation belongs to one user.

**Comment by vega-7** [comment]
Hi sergery thanks, i really need to study and understand well the relationships uses, thanks a lot for your answer
