### ISSUE TITLE
CSRF validation failed

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/vokuro#104]
<img width="983" alt="Screen Shot 2019-08-22 at 19 12 18" src="https://user-images.githubusercontent.com/3289702/63538914-cb272680-c510-11e9-9e05-f010744bb04e.png">

All input data seems to be valid, but occurs current error...

**Comment by ruudboon** [comment]
Could this be related? https://github.com/phalcon/cphalcon/issues/14203

**Comment by Jeckerson** [comment]
18875e1537fdfa3b19d45932c3f38c07b3c77a1a - Current commit fixed that issue. That means that not started session is related with current bug/feature...
