### ISSUE TITLE
Write tests + rewrites [Iteration 5]

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/vokuro#107]
- [x] Change domain from `phalconphp.com` to `phalcon.io`
- [x] Generate new password hashes and put original in migrations seed
- [x] Write acceptance tests
- [x] Add namespaces for db seeds and migrations
- [x] Add .htrouter.php (https://pastebin.com/raw/7h3ni5pb)
- [x] Rewrite service providers as separate classes
- [x] PSR-4
- [x] Refactor code to PHP 7.x syntax
- [x] Reach until level 3 in psalm
- [x] Update `@deprecated` code
- [x] Review and Update README
- [x] Setup travis
- [x] ~Composer project installation~ (http://php-pds.com/)

**Comment by ruudboon** [comment]
Setup travis with database initializing?
Upgrade phpunit/codeception

**Comment by Jeckerson** [comment]
> Setup travis with database initializing?
Yes

> Upgrade phpunit/codeception
Already latest version in `4.0.x` branch

**Comment by Jeckerson** [comment]
Implemented in #110
