### ISSUE TITLE
More tests + extra features [Iteration 6] && [Iteration 7]

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/vokuro#116]
- [x] Normalize composer.json (https://github.com/localheinz/composer-normalize)
- [x] Add PHPCS to travis with PSR-2 rules
- [x] Composer project installation (http://php-pds.com/)
- [x] Fill community profile (https://github.com/phalcon/vokuro/community)
- [x] ~Database tables review and refactor through migrations~
- [x] Code refactor + Unit tests
- [x] Code refactor + Functional tests
- [x] Fix email confirmation

**Comment by ruudboon** [comment]
Looks good!

**Comment by Jeckerson** [comment]
Implemented.
