### ISSUE TITLE
Vokuro Not working

### ISSUE THREAD

**Issue by Vecqrsh** [phalcon/vokuro#155]
it is saying, 
Fatal error: Declaration of Vokuro\Providers\AclProvider::register(Phalcon\Di\DiInterface $di): void must be compatible with Phalcon\Di\ServiceProviderInterface::register(Phalcon\DiInterface $di) in /home/rakmyat/public_html/sea/src/Providers/AclProvider.php on line 20
What can we do ?

**Comment by delphianer** [comment]
Hi Vecqrsh, 
Vocuro is working fine and I started a project just a few days ago that is based on vokuro. 

Can you provide us some environmental information and your webserver settup (I mean, do you use apache and your DocumentRoot is public and so on) ?
greetz

**Comment by Jeckerson** [comment]
You need to use the latest version of phalcon.
