### ISSUE TITLE
Docker exited with code 139

### ISSUE THREAD

**Issue by twarnicki** [phalcon/vokuro#159]
Hello, I tried to test Vokuro on Docker as suggested in tutorial. I ommited problematic Codeception in composer. I sucesfuly migrated&seeded with phinx.
Docker crashes with ' exited with code 139' ( container received SIGSEGV ) whenever i try to login or register user. 
I tried to look for some  more clues but its hard on docker.

**Comment by Jeckerson** [comment]
Related https://github.com/phalcon/cphalcon/issues/15107

**Comment by twarnicki** [comment]
Problem still exists with nightly version. 
"vokuro_app exited with code 139" after accessing DB
