### ISSUE TITLE
Wrong TYPE for attempted in failed_logins

### ISSUE THREAD

**Issue by Frederik10k** [phalcon/vokuro#24]
Hei, the field "attempted" in failed_logins has the TYPE TINYINT (5).
But Vokuro uses a timestamp on this field.

I changed it to INT (10) in my case.
So now the login - throtteling works. :)

greetings

**Comment by sergeysviridenko** [comment]
field `attempted` in table `failed_logins` is int(10) for MySQL and `integer` for Postgresql. Maybe we can close this issue?
