### ISSUE TITLE
Potential security problem on case-sensitive filesystems

### ISSUE THREAD

**Issue by Frederik10k** [phalcon/vokuro#26]
Hei,

Vokuro does not check the foldernames of the views-folders.

While http://vokuro.phalconphp.com/users is not accessible without logging in, http://vokuro.phalconphp.com/uSers (uppercase S) delivers some private content such as the menu for logged in users.

**Comment by sergeysviridenko** [comment]
I couldn't reproduce. When I've gone for this link `http://vokuro.phalconphp.com/uSers` I've had `Internal 500`
