### ISSUE TITLE
AmazonSES construct has changed

### ISSUE THREAD

**Issue by alimnios72** [phalcon/vokuro#28]
Latest 1.x aws sdk for php no longer support this sintax:

 new \AmazonSES(
                $this->config->amazon->AWSAccessKeyId,
                $this->config->amazon->AWSSecretKey
            );

It should be replaced with something like this:

 new \AmazonSES(array(
                "key"=>$this->config->amazon->AWSAccessKeyId,
                "secret"=>$this->config->amazon->AWSSecretKey
            ));

**Comment by sergeysviridenko** [comment]
New syntax for AmazonSES looks
```
$this->amazonSes = new \AmazonSES(
                [
                    'key'    => $this->config->amazon->AWSAccessKeyId,
                    'secret' => $this->config->amazon->AWSSecretKey
                ]
            );
```

Maybe this issue can be closed?
