### ISSUE TITLE
Usage without emails

### ISSUE THREAD

**Issue by alec-w** [phalcon/vokuro#44]
**Make sending emails optional**

Most users will be using this to get to grips with PhalconPHP on a test environment without the ability to send emails. The addition of a boolean to the config files should sort this - when true, emails are sent as normal; when false, emails are not sent (and accounts do not require being activated by an email link, etc).

Started this already, will add this week.

**Comment by dschissler** [comment]
Can you make a pull request for that with true as the default?

**Comment by alec-w** [comment]
Yes I will, that was my intention.
