### ISSUE TITLE
Record in "user_remember_tokens" is not remove after call remove()

### ISSUE THREAD

**Issue by dsouksavatd** [phalcon/vokuro#63]
after working on Auth lib for a while I just noticed that when we use Remember Me on login process all cookies will be remove after we call remove() but why the token record is still in the table? I can't figure out what purpose for keeping it there, anyways I have put 2 lines of code into remove() function in order to remove those record from table after logout
```
$token = $this->cookies->get('RMT')->getValue();
UserRememberTokens::findFirstByToken($token)->delete();
$this->cookies->get('RMT')->delete();
```

**Comment by sergeyklay** [comment]
Can you take a look

**Comment by dsouksavatd** [comment]
https://github.com/phalcon/vokuro/pull/64
