### ISSUE TITLE
deprecated Tag::resetInput()

### ISSUE THREAD

**Issue by chipco** [phalcon/vokuro#80]
Using phalcon 3.3.1, there's a warning about the way forms are cleared. Create a new user to reproduce.

```
PHP Deprecated:  Function Phalcon\Tag::resetInput() is deprecated
```

**Comment by iRickyJ** [comment]
This is also happening with Phalcon 3.3.2, its just happening everywhere when Tag:resetInput is used.

**Comment by sergeyklay** [comment]
Fixed in the `development` branch. Feel free to open a new issue if the problem appears again. Thank you for contributing.
