### ISSUE TITLE
Why its tutorial was never completed ?

### ISSUE THREAD

**Issue by iRickyJ** [phalcon/vokuro#82]
I started learning Phalcon few months back and everything was good till I reached Vokuro, it was incomplete and then I thought to continue learning phalcon some other time. So I again decided to get back to phalcon few weeks ago, have been going through lots of docs and references, but I wish if Vokuro had proper tutorial like INVO then would have saved a lots of confusion I had earlier. Specially if one is first timer to any Framework (not only phalcon).

I am not yet strong enough in Phalcon to complete tutorial docs myself, I wish if someone else with proper command over Phalcon can do it. It will really help new starters to get better Idea about this impressive framework.

**Comment by niden** [comment]
Let me check it out @iRickyJ . It has been a while since I worked with that repository/tutorial

In the meantime you can find us on discord (https://phalcon.link/discord) if you have urgent querstions

**Comment by Jeckerson** [comment]
https://docs.phalcon.io/4.0/en/tutorial-vokuro - work in progress, but most part already done and described.

**Comment by niden** [comment]
@Jeckerson once you are done with Vokuro, please have a quick read through the tutorial in case we missed something.

**Comment by Jeckerson** [comment]
Updated documentation/tutorial - https://docs.phalcon.io/4.0/en/tutorial-vokuro
