### ISSUE TITLE
userAgent field too short

### ISSUE THREAD

**Issue by lusorio** [phalcon/vokuro#83]
The userAgent field in the schemas is too short.

Chrome in OSX El Capitan gives 

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

which won't fit in varchar(120)

I've tried to create a pull request, but I'm getting an auth error.

**Comment by sergeyklay** [comment]
Fixed in the `development` branch. Feel free to open a new issue if the problem appears again. Thank you for contributing.
