### ISSUE TITLE
Someone explain me this line

### ISSUE THREAD

**Issue by xerron** [phalcon/vokuro#97]
https://github.com/phalcon/vokuro/blob/901c959af643142ebaa783e04e56c0310fac3918/app/library/Mail/Mail.php#L73

**Comment by niden** [comment]
https://docs.phalconphp.com/hu/3.2/api/Phalcon_Mvc_View_Simple

**Comment by niden** [comment]
```
public getContent ()
Returns cached output from another view stage
```

**Comment by xerron** [comment]
Sorry, do not explain me well.

In this function there are two return. That inea never runs. Because it is there?

```php
return $this->view->getRender('emailTemplates', $name, $parameters, function ($view) {
            $view->setRenderLevel(View::LEVEL_LAYOUT);
        });

return $view->getContent();
````
