### ISSUE TITLE
phalcon v4

### ISSUE THREAD

**Issue by davidov7** [phalcon/vokuro#98]
Wrong number of parameters
#0 /var/www/html/public/index.php(41): Phalcon\Mvc\Application->handle()
#1 {main}

please, update this repository phalcon v4

**Comment by niden** [comment]
That is the goal @davidov7. We are concentrating on getting Phalcon at least to beta before working on the sample applications.

**Comment by sitchi** [comment]
https://github.com/sitchi/vokuro-v4 	Compatible phalcon v4.0.0-alpha.4

**Comment by niden** [comment]
@sitchi do you want to issue a PR to a branch on the vokuro repository say v4 branch for this?

**Comment by sitchi** [comment]
@niden yes

**Comment by sitchi** [comment]
https://github.com/sitchi/vokuro/tree/4.0.x Maybe so?

**Comment by ruudboon** [comment]
@sitchi I created a 4.0.x branch on this repo. Can you create a pull request to that branch? https://github.com/phalcon/vokuro/tree/4.0.x

**Comment by ruudboon** [comment]
@sitchi Now with beta.2 out we would like make sure Vokuru is also v4 ready. Do you have time to create a pull to the 4.0.x branch?

**Comment by Jeckerson** [comment]
Fixed and merged [here](https://github.com/phalcon/vokuro/pull/103), into `4.0.x` branch.
